name: flutter_paint
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies: 
  flutter_lints: ^1.0.4    

flutter:
  uses-material-design: true
